### PR TITLE
Use the Statix rumtime config

### PR DESCRIPTION
**Pull request by objectuser**
This leverages the `runtime_config` option on Statix in an attempt to avoid the error:

```
(RuntimeError) the current configuration for Rheostat.Internal.StatixAdapter differs from the one that was given during the compilation.
```

### CODE REVIEW

**Comment by hdeters** [comment]
Looks good. This will break existing usages though, correct? It will use `[]` as the opts and not whatever prefix is specified in the config? Wondering if there's a backwards compatible option.

**Comment by objectuser** [comment]
From reading [the code](https://github.com/lexmag/statix/blob/master/lib/statix.ex#L410) it looks like the options will be merged in, so I _think_ it'll work. The options are optional but still accepted.

What do you think?

**Comment by hdeters** [comment]
Ah, that does look promising. Well I'll give it a shot with this branch and see if that's the case.

**Comment by hdeters** [comment]
I believe we have successful liftoff. Just deployed to staging with this branch and am seeing stats in datadog with kafka-s3 prefix.

**Review by hdeters — APPROVED** [review]

**Pull request merged**
